/*
 * generated by Xtext
 */
package org.eclipse.gemoc.bflow;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BFlowRuntimeModule extends org.eclipse.gemoc.bflow.AbstractBFlowRuntimeModule {

}
