/*******************************************************************************
 * Copyright (c) 2015, 2017  I3S Laboratory  and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     I3S Laboratory - initial API and implementation
 *******************************************************************************/
/*
* generated by Xtext
*/
package org.eclipse.gemoc.bflow;

import org.eclipse.gemoc.bflow.BFlowStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BFlowStandaloneSetup extends BFlowStandaloneSetupGenerated{

	public static void doSetup() {
		new BFlowStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

