/**
 * generated by Xtext
 */
package org.gemoc.bcool.model.xtext.serializer;

import org.gemoc.bcool.model.xtext.serializer.AbstractBCOoLSemanticSequencer;

@SuppressWarnings("all")
public class BCOoLSemanticSequencer extends AbstractBCOoLSemanticSequencer {
}
