/**
 * generated by Xtext
 */
package org.gemoc.bcool.validation;

import org.gemoc.bcool.validation.AbstractBCOoLLibValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class BCOoLLibValidator extends AbstractBCOoLLibValidator {
}
