/**
 * generated by Xtext
 */
package org.gemoc.bcool.serializer;

import org.gemoc.bcool.serializer.AbstractBCOoLLibSyntacticSequencer;

@SuppressWarnings("all")
public class BCOoLLibSyntacticSequencer extends AbstractBCOoLLibSyntacticSequencer {
}
