/**
 * generated by Xtext
 */
package org.gemoc.bcool.serializer;

import org.gemoc.bcool.serializer.AbstractBCOoLLibSemanticSequencer;

@SuppressWarnings("all")
public class BCOoLLibSemanticSequencer extends AbstractBCOoLLibSemanticSequencer {
}
