/*
 * generated by Xtext
 */
package org.eclipse.gemoc.bcool.ui.contentassist

import org.eclipse.gemoc.bcool.ui.contentassist.AbstractBCOoLLibProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class BCOoLLibProposalProvider extends AbstractBCOoLLibProposalProvider {
}
