/**
 * generated by Xtext
 */
package org.gemoc.bcool.model.xtext.validation;

import org.gemoc.bcool.model.xtext.validation.AbstractBCOoLValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class BCOoLValidator extends AbstractBCOoLValidator {
}
