/*
 * generated by Xtext
 */
package org.eclipse.gemoc.bcool.model.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class BCOoLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/eclipse/gemoc/bcool/model/xtext/parser/antlr/internal/InternalBCOoL.tokens");
	}
}
