/*
 * generated by Xtext
 */
package org.gemoc.bcool.model.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BCOoLRuntimeModule extends org.gemoc.bcool.model.xtext.AbstractBCOoLRuntimeModule {

}
