/*
 * generated by Xtext
 */
package org.eclipse.gemoc.bcool;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BCOoLLibRuntimeModule extends org.eclipse.gemoc.bcool.AbstractBCOoLLibRuntimeModule {

}
