/*
* generated by Xtext
*/
package org.eclipse.gemoc.bcool;

import org.eclipse.gemoc.bcool.BCOoLLibStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BCOoLLibStandaloneSetup extends BCOoLLibStandaloneSetupGenerated{

	public static void doSetup() {
		new BCOoLLibStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

