/*******************************************************************************
 * Copyright (c) 2015, 2017  I3S Laboratory  and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     I3S Laboratory - initial API and implementation
 *******************************************************************************/
/*
 * generated by Xtext
 */
package org.eclipse.gemoc.bcool.model.xtext;
/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BCOoLRuntimeModule extends org.eclipse.gemoc.bcool.model.xtext.AbstractBCOoLRuntimeModule {

	//public Class<? extends XMemberFeatureCallImpl> xbaseCompiler{
	//	return TemplateCompiler.class;
	//}
	
	
	
//	@Override
//	public Class<? extends ITypeComputer> bindITypeComputer() {
//		return BCOoLTypeComputer.class;
//	}
	
//	@Override
//	public Class<? extends XbaseBatchScopeProvider> bindXbaseBatchScopeProvider() {
//		return BCOoLBatchScopeProvider.class;
//	}
//	
//	@Override
//	public Class<? extends IScopeProvider> bindIScopeProvider() {
//		return BCOoLScopeProvider.class;
//	}
	
	//@Override
	//public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
	//	return NullGlobalScopeProvider.class;
	//}
	
}

