/*
* generated by Xtext
*/
package org.eclipse.gemoc.bcool.model.xtext;

import org.eclipse.gemoc.bcool.model.xtext.BCOoLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class BCOoLStandaloneSetup extends BCOoLStandaloneSetupGenerated{

	public static void doSetup() {
		new BCOoLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

