/*******************************************************************************
 * Copyright (c) 2015, 2017  I3S Laboratory  and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *     I3S Laboratory - initial API and implementation
 *******************************************************************************/
/*
 * generated by Xtext
 */
package org.eclipse.gemoc.bcool.model.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class BCOoLUiInjectorProvider implements IInjectorProvider {

	public Injector getInjector() {
		return org.eclipse.gemoc.bcool.model.xtext.ui.internal.BCOoLActivator.getInstance().getInjector("org.eclipse.gemoc.bcool.model.xtext.BCOoL");
	}

}
