/*
 * generated by Xtext
 */
package org.eclipse.gemoc.bcool.model.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class BCOoLUiInjectorProvider implements IInjectorProvider {

	public Injector getInjector() {
		return org.eclipse.gemoc.bcool.model.xtext.ui.internal.BCOoLActivator.getInstance().getInjector("org.eclipse.gemoc.bcool.model.xtext.BCOoL");
	}

}
