/**
 * generated by Xtext
 */
package org.gemoc.bcool.model.xtext.serializer;

import org.gemoc.bcool.model.xtext.serializer.AbstractBCOoLSyntacticSequencer;

@SuppressWarnings("all")
public class BCOoLSyntacticSequencer extends AbstractBCOoLSyntacticSequencer {
}
