/*
 * generated by Xtext
 */
package org.eclipse.gemoc.bflow.ui.contentassist

import org.eclipse.gemoc.bflow.ui.contentassist.AbstractBFlowProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class BFlowProposalProvider extends AbstractBFlowProposalProvider {
}
